jobs:
  check:
    name: Main
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Get Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./verify/action

name: Run

on:
  schedule:
    - cron: "0 1/3 * * *"
